### ISSUE TITLE
Attribution scores vs importance scores

### ISSUE THREAD

**Issue by due23** [jmschrei/tfmodisco-lite#1]
Hi!

I'm trying to run either TF-MoDISco or this newer tfmodisco-lite for interpretation of a CNN model I have trained on enhancer sequences. I've managed to calculate the importance scores and hypothetical importance scores of my one-hot encoded enhancer sequences following the code from [this notebook](https://github.com/kundajelab/shap/blob/276bb8cae899a79dedab15c294cd440e57d5695e/notebooks/deep_explainer/Tensorflow%20DeepExplainer%20Genomics%20Example%20With%20Hypothetical%20Importance%20Scores.ipynb) using DeepExplainer.

For tfmodisco-lite I'm slightly confused as to what I'm meant to be inputting for the attributions. Are the attributions the same as the importance scores or some combination of the importance scores and hypothetical importance scores? If not, how do you obtain these attributions?

**Comment by jmschrei** [comment]
Howdy. Importance scores and attribution scores are synonyms. You should be inputting the one-hot encoded sequence and the hypothetical importance scores.

**Comment by ilyes495** [comment]
Hi,
I'm trying to generate the hypothetical importance scores using both DeepExplainer and GradientExplainer following [this notebook](https://github.com/kundajelab/shap/blob/276bb8cae899a79dedab15c294cd440e57d5695e/notebooks/deep_explainer/Tensorflow%20DeepExplainer%20Genomics%20Example%20With%20Hypothetical%20Importance%20Scores.ipynb), but I got an error saying:
> TypeError: __init__() got an unexpected keyword argument 'combine_mult_and_diffref'

should downgrade all my packages to work the examples?or there is a way to do that with the current versions?

Thank you in advance
