### ISSUE TITLE
Motifs missing when input sequence less than 400 bp

### ISSUE THREAD

**Issue by ziwei-75** [jmschrei/tfmodisco-lite#11]
If the user doesn't set the -w option, Modisco-lite may produce different results compared to standard Modisco when the input sequence is less than 400 bp. It would be good for the program to automatically account for this scenario, either by raising an error or by using the provided sequence length.

**Comment by jmschrei** [comment]
v2.0.7 will raise an error if the window is longer than the sequence -- or, more specifically, if the extracted subsequences are not of the same size as the window.

**Comment by 09oulin** [comment]
@ziwei-75 @jmschrei 
Hello, I recently used the modisco motifs to find motifs. The input is the count_contribs_scores.h5 created from chrombpnet contribs function. The sequence should be 2114bp, so I set the -window to 501(the peak length), but there appeared an error:
Traceback (most recent call last):
  File "/miniconda3/envs/chrombpnetv8/bin/modisco", line 109, in <module>
    raise ValueError("Window ({}) cannot be ".format(args.window) +
ValueError: Window (501) cannot be longer than the sequences.

Do you know the reason? How can I solve this problem? By the way, I checked the script in the chrombpnet find motif part, it sets the -window to 500.

I am really confused, please give me some advice. Thanks a lot!

**Comment by jmschrei** [comment]
There may be an off-by-one error here. Does `-window 500` work?

**Comment by 09oulin** [comment]
Yes, it works when I changed the -window to 500. I don't understand the reason behind it. Could you explain the off-by-one error further?
