### ISSUE TITLE
Arial Rounded not available on my system

### ISSUE THREAD

**Issue by mmtrebuchet** [jmschrei/tfmodisco-lite#4]
On line 164 in report.py, you specify that the logo should be made with the Arial Rounded font, which is not available on my system. This results in pages and pages of "findfont: Font family 'Arial Rounded' not found." errors. Removing the argument fixes the issue, and the generated logos look good to me.

**Comment by jmschrei** [comment]
This should be fixed on v2.0.5. Sorry for the delay.
