### ISSUE TITLE
Create reports without meme database

### ISSUE THREAD

**Issue by mmtrebuchet** [jmschrei/tfmodisco-lite#5]
If I don't much care to compare my motifs to a database, it would still be nice to be able to generate a report. It would be nice to make the -m argument to report optional. 
(It would also be nice if the documentation were very clear about exactly what file is expected for the -m argument, since it's a very particular format.)

**Comment by shtoneyan** [comment]
Hello, I am trying to generate a report too but get an error message when I input a .txt file (e.g. this one - https://jaspar.genereg.net/download/data/2022/CORE/JASPAR2022_CORE_vertebrates_non-redundant_pfms_jaspar.txt). I was wondering if one of you know what the particular format is that we need to use for this file. Thank you!
