### ISSUE TITLE
problem in tfmodisco input

### ISSUE THREAD

**Issue by GGboy-Zzz** [jmschrei/tfmodisco-lite#52]
Hello,
   Thank you so much for your amazing work!
   I'm not sure what's the difference between profile_socre.h5 and counts_score.h5 input. Can I use any one of them as tfmodisco input, or which one is suggested? 
   Thanks in advance.

Best wishes.

**Comment by mmtrebuchet** [comment]
As far as modisco is concerned, there's no difference. Those two files stem from two ways that we interpret BPNet-style models - counts scores interpret the total readout over a whole window, and profile scores measure the spikiness of the profile in a region. By running modisco on counts, we get the motifs that contribute to the number of reads, and by running modisco on profile we get motifs that determine the shape of the profile. If you're not using BPNet (or one of its derivatives), then you can just provide whatever you have. If you are using BPNet, then I'd suggest running modisco twice - once on the profile and once on the counts.

**Comment by jmschrei** [comment]
As @mmtrebuchet mentioned, those two files are derived from calculating DeepLIFT/SHAP attributions on two outputs from BPNet-style models. tf-modisco can be run on any form of attributions -- including DeepLIFT/SHAP on other models, but also including other forms of attributions like in silico saturation mutagenesis or others.

**Comment by GGboy-Zzz** [comment]
Thank you for your prompt response, I will running modisco on both, and compare the result difference. Thank you again！
