### ISSUE TITLE
Turn off reverse complements

### ISSUE THREAD

**Issue by Turakar** [jmschrei/tfmodisco-lite#56]
It would be useful if a user could pass `revcomp=False` to disable reverse complementing for matching. In my use case, reverse complements should not match each other, but be considered separate. Could this be added to the library?

It seems like updating `_align_patterns()` should be enough?

**Comment by jmschrei** [comment]
Conceptually, it could be done. However, I think this is built-in to many methods, the most important being the seqlet similarity scores, and I don't have the bandwidth to add this feature. Sorry about that.

**Comment by Turakar** [comment]
Not considering possible performance improvements - is it wrong to only change `_align_patterns()`?

**Comment by jmschrei** [comment]
Yeah, you'd need too also change the seqlet similarity score in at least https://github.com/jmschrei/tfmodisco-lite/blob/main/modiscolite/affinitymat.py#L67. I don't remember all the places it would matter -- it's been a while since I've looked at the code.
