### ISSUE TITLE
tabs vs spaces 

### ISSUE THREAD

**Issue by hopdebee** [jmschrei/tfmodisco-lite#9]
Hi Jacob,

Minor annoyance: I noticed that the codebase is built out of files where you use tabs and not spaces. 
[Guido said](https://peps.python.org/pep-0008/#tabs-or-spaces) that spaces are the way to go, so probably a lot of people will get indentation errors if they tweak something to the code. I successfully changed all the leading (`-i` in the command) tabs in the `modiscolite` folder to 4 spaces with this oneliner: ([via](https://stackoverflow.com/questions/11094383/how-can-i-convert-tabs-to-spaces-in-every-file-of-a-directory)) 
`find . -name '*.py' ! -type d -exec bash -c 'expand -i -t 4 "$0" > /tmp/e && mv /tmp/e "$0"' {} \;`

**Comment by jmschrei** [comment]
Thanks for pointing this out. I use tabs because spaces don't make sense to me. Feel free to convert to spaces if you'd like to change things locally. I think that most editors have built-in converters between the two.
